version: '3.7'

services:

  django:
    container_name: psihofon-django
    build:
      context: .
      dockerfile: django.Dockerfile
    env_file:
      - .env
    ports:
      - "48100:8000"
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src

  postgres:
    container_name: psihofon-postgres
    image: library/postgres:13.4-alpine
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USERNAME}" ]
      timeout: 45s
      interval: 10s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    container_name: psihofon-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
    ports:
      - "48101:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data:
  postgres-data:
