# Generated by Django 3.2.7 on 2021-09-25 14:17

import django.contrib.postgres.fields.citext
from django.db import migrations, models
from django.contrib.postgres.operations import CITextExtension


class Migration(migrations.Migration):
    dependencies = [
        ('psihofon', '0001_initial'),
    ]

    operations = [
        CITextExtension(),
        migrations.CreateModel(
            name='CrisisExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_sr_latn', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('description_en', models.TextField(null=True, verbose_name='description')),
                ('description_sr_latn', models.TextField(null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'CrisisExercise',
                'verbose_name_plural': 'CrisisExercises',
            },
        ),
        migrations.CreateModel(
            name='SelfEmpowermentExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_sr_latn', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('week_number', models.SmallIntegerField(verbose_name='week number')),
                ('preparation', models.TextField(verbose_name='preparation')),
                ('preparation_en', models.TextField(null=True, verbose_name='preparation')),
                ('preparation_sr_latn', models.TextField(null=True, verbose_name='preparation')),
                ('description', models.TextField(verbose_name='description')),
                ('description_en', models.TextField(null=True, verbose_name='description')),
                ('description_sr_latn', models.TextField(null=True, verbose_name='description')),
                ('explanation', models.TextField(verbose_name='explanation')),
                ('explanation_en', models.TextField(null=True, verbose_name='explanation')),
                ('explanation_sr_latn', models.TextField(null=True, verbose_name='explanation')),
                ('duration_description', models.TextField(default='', verbose_name='duration description')),
                ('duration_description_en',
                 models.TextField(default='', null=True, verbose_name='duration description')),
                ('duration_description_sr_latn',
                 models.TextField(default='', null=True, verbose_name='duration description')),
            ],
            options={
                'verbose_name': 'Self Empowerment Exercise',
                'verbose_name_plural': 'Self Empowerment Exercises',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=django.contrib.postgres.fields.citext.CIEmailField(
                db_index=True, max_length=254, unique=True,
                verbose_name='email'
            ),
        ),
    ]
