# Generated by Django 3.2.7 on 2021-09-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psihofon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
