# Generated by Django 3.2.7 on 2021-09-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psihofon', '0002_auto_20210925_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrisisExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
            ],
            options={
                'verbose_name': 'CrisisExercise',
                'verbose_name_plural': 'CrisisExercises',
            },
        ),
    ]
