# Generated by Django 3.2.7 on 2021-09-25 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psihofon', '0002_auto_20210925_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentalState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_sr_latn', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('exercise_list_label', models.CharField(max_length=255, verbose_name='exercise list label')),
                ('exercise_list_label_en', models.CharField(max_length=255, null=True, verbose_name='exercise list label')),
                ('exercise_list_label_sr_latn', models.CharField(max_length=255, null=True, verbose_name='exercise list label')),
            ],
            options={
                'verbose_name': 'Mental State',
                'verbose_name_plural': 'Mental States',
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='description')),
                ('description_en', models.TextField(null=True, verbose_name='description')),
                ('description_sr_latn', models.TextField(null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Questionnaire',
                'verbose_name_plural': 'Questionnaires',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('text_en', models.TextField(null=True, verbose_name='text')),
                ('text_sr_latn', models.TextField(null=True, verbose_name='text')),
                ('order_number', models.SmallIntegerField(verbose_name='order number')),
                ('mental_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='psihofon.mentalstate', verbose_name='mental state')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psihofon.questionnaire', verbose_name='questionnaire')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('text_en', models.TextField(null=True, verbose_name='text')),
                ('text_sr_latn', models.TextField(null=True, verbose_name='text')),
                ('order_number', models.SmallIntegerField(verbose_name='order number')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psihofon.questionnaire', verbose_name='questionnaire')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
    ]
