# Generated by Django 3.2.7 on 2021-09-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psihofon', '0002_auto_20210925_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfEmpowermentExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_sr_latn', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('week_number', models.SmallIntegerField(verbose_name='week number')),
                ('preparation', models.TextField(verbose_name='preparation')),
                ('preparation_en', models.TextField(null=True, verbose_name='preparation')),
                ('preparation_sr_latn', models.TextField(null=True, verbose_name='preparation')),
                ('description', models.TextField(verbose_name='description')),
                ('description_en', models.TextField(null=True, verbose_name='description')),
                ('description_sr_latn', models.TextField(null=True, verbose_name='description')),
                ('explanation', models.TextField(verbose_name='explanation')),
                ('explanation_en', models.TextField(null=True, verbose_name='explanation')),
                ('explanation_sr_latn', models.TextField(null=True, verbose_name='explanation')),
            ],
            options={
                'verbose_name': 'Self Empowerment Exercise',
                'verbose_name_plural': 'Self Empowerment Exercises',
            },
        ),
    ]
