# Generated by Django 3.2.7 on 2021-09-25 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psihofon', '0003_answer_mentalstate_question_questionnaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentalStateExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_sr_latn', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('description_en', models.TextField(null=True, verbose_name='description')),
                ('description_sr_latn', models.TextField(null=True, verbose_name='description')),
                ('recommendation', models.TextField(verbose_name='recommendation')),
                ('recommendation_en', models.TextField(null=True, verbose_name='recommendation')),
                ('recommendation_sr_latn', models.TextField(null=True, verbose_name='recommendation')),
                ('mental_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psihofon.mentalstate', verbose_name='mental state')),
            ],
            options={
                'verbose_name': 'Mental State Exercise',
                'verbose_name_plural': 'Mental State Exercises',
            },
        ),
    ]
