# Generated by Django 3.2.7 on 2021-09-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psihofon', '0003_crisisexercise'),
        ('psihofon', '0003_selfempowermentexercise'),
    ]

    operations = [
    ]
