# Generated by Django 3.2.7 on 2021-09-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psihofon', '0004_merge_20210925_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisisexercise',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='crisisexercise',
            name='description_sr_latn',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='crisisexercise',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='crisisexercise',
            name='title_sr_latn',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
    ]
