# Generated by Django 3.2.7 on 2021-09-25 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psihofon', '0004_mentalstateexercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='crisisexercise',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='crisisexercise',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='mentalstate',
            name='exercise_list_label_en',
        ),
        migrations.RemoveField(
            model_name='mentalstate',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='mentalstateexercise',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='mentalstateexercise',
            name='recommendation_en',
        ),
        migrations.RemoveField(
            model_name='mentalstateexercise',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='city_en',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='selfempowermentexercise',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='selfempowermentexercise',
            name='duration_description_en',
        ),
        migrations.RemoveField(
            model_name='selfempowermentexercise',
            name='explanation_en',
        ),
        migrations.RemoveField(
            model_name='selfempowermentexercise',
            name='preparation_en',
        ),
        migrations.RemoveField(
            model_name='selfempowermentexercise',
            name='title_en',
        ),
        migrations.AlterField(
            model_name='answer',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='psihofon.questionnaire', verbose_name='questionnaire'),
        ),
        migrations.AlterField(
            model_name='mentalstateexercise',
            name='mental_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='psihofon.mentalstate', verbose_name='mental state'),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='psihofon.questionnaire', verbose_name='questionnaire'),
        ),
    ]
