export enum AppRoute {
  QUIZ = 'Quiz',
  SECOND_EXCERCISES = 'Second Excercises',
  DRAWER = 'Drawer',
  INTRO_MENU = 'Intro Menu',
  ORGANIZATIONS_LIST = 'Organizations List',
  ORGANIZATIONS_NAVIGATOR = 'Organizations Navigators',
  ANALYTICS_QUIZ_RESULTS = 'Analytics Quiz Results',
  EXCERCISE_OVERVIEW = 'Excercise Overview',
  FIRST_TYPE_EXERCISE_NAVIGATOR = 'First type exercise navigator',
  FIRST_TYPE_EXCERCISE_CHECK = 'First Type Excercise Check',
  FIRST_TYPE_EXERCISE_FIRST_WEEK = 'First Type Exercise First Week',
  CRISIS = 'Crisis',
  SCALE_EXPLANATION = 'Scale Explanation',
  CRISIS_EXERCISES = 'Crisis Exercises',
  EXERCISE_LIST = 'Exercise List',
  CRISIS_EXERCISE_SCREEN = 'Crisis Exercise Screen',
}
